# Generated by Django 2.1.5 on 2019-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labels_key',
            fields=[
                ('labels', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='标签')),
                ('main_key', models.CharField(max_length=30, verbose_name='主属性')),
                ('second_key', models.CharField(max_length=30, verbose_name='次要属性')),
            ],
        ),
    ]
