# Generated by Django 2.1.5 on 2019-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='algo_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_name', models.CharField(max_length=30, verbose_name='算法名称')),
                ('algo_content', models.TextField(verbose_name='内容')),
                ('algo_date', models.DateField(verbose_name='添加日期')),
            ],
        ),
    ]
