# Generated by Django 2.1.5 on 2019-03-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0002_algo_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algo_module',
            name='algo_date',
            field=models.DateField(auto_now_add=True, verbose_name='添加日期'),
        ),
    ]
