# Generated by Django 2.1.5 on 2019-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0003_auto_20190328_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algo_module',
            name='algo_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日期'),
        ),
    ]
