# Generated by Django 2.1.5 on 2019-04-03 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0004_auto_20190328_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='algo_module',
            name='algo_return',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='返回值类型'),
            preserve_default=False,
        ),
    ]
