# Generated by Django 2.1.5 on 2019-04-01 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('path', '0004_auto_20190328_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('project_file', models.FilePathField(verbose_name='外部数据')),
                ('project_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('project_layout', models.CharField(max_length=30, verbose_name='布局')),
                ('project_algo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='path.algo_module')),
            ],
        ),
    ]
