# Generated by Django 2.1.5 on 2019-04-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_module',
            name='project_text',
            field=models.TextField(default='', verbose_name='描述'),
        ),
    ]
