# Generated by Django 2.1.5 on 2019-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_module_project_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_module',
            name='project_file',
            field=models.FilePathField(path='/upload/', verbose_name='外部数据'),
        ),
    ]
