# Generated by Django 2.1.5 on 2019-04-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190401_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_module',
            name='project_file',
            field=models.FilePathField(path='./upload/', verbose_name='外部数据'),
        ),
    ]
